### ISSUE TITLE
Error with example.qmd

### ISSUE THREAD

**Issue by beckjacob** [surveydown-dev/surveydown#83]
I  got this error message when trying to run the example.qmd on my windows computer:

processing file: example.qmd
                                                                                                            
output file: example.knit.md

pandoc 
  to: html
  output-file: example.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  server: shiny
  
Error running filter C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:
sh: createProcess: does not exist (No such file or directory)
stack traceback:
	...vey\_extensions\surveydown-dev\surveydown\surveydown.lua:8: in local 'chunk'
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:4077: in local 'callback'
	[string "..."]:1789: in function <[string "..."]:1787>
	(...tail calls...)
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:368: in function 'make_wrapped_user_filters'
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:15399: in main chunk

**Comment by jhelvy** [comment]
Did you already install the surveydown R package? It looks like you have the extension in place but perhaps not the R package.

**Comment by beckjacob** [comment]
Yes, I installed it using this command:

remotes::install_github("surveydown-dev/surveydown")

**Comment by jhelvy** [comment]
Can you make sure that you follow steps one and two on the getting started guide? 

https://surveydown.org/get-started

I'm just trying to make sure that everything is set up properly. If you've done all of that and this is still happening, then we'll have to keep working to figure out what's wrong.

You can also check that you have the most up-to-date version of the package and extension 

https://surveydown.org/installation#version-control

**Comment by beckjacob** [comment]
I ensured all this (see output below) but the error persists

```
> surveydown::sd_check_versions()
surveydown R package (local): 0.2.0
surveydown R package (latest): 0.2.0
surveydown Quarto ext (local): 0.2.0
surveydown Quarto ext (latest): 0.2.0

Both the R package and Quarto extension are up to date.
```

**Comment by pingfan-hu** [comment]
Hi @beckjacob , I used my PC to load one of our demo surveys but couldn't see any problem. Can you share with us your repo so I can do more debugging?

**Comment by jhelvy** [comment]
We've now found at least one example where there is an issue with windows machines, but not all windows as some are working. We'll keep searching for the source of the problem, but we believe it has to do with the extension lua file looking for the R package and not being able to find it on some windows machines.

**Comment by jhelvy** [comment]
Okay I think we have a fix now, though I'm not certain it is working. Can you install both the latest package and extension and try it again? You can do both quickly with this:

```r
surveydown::sd_update_surveydown()
```

surveydown works with two lua files. One (called `surveydown.lua`) lives in the extension, and all it does is load the one that lives inside the installed package (called `main.lua`). We did this so that all the main logic and other related files will remain version controlled within the package, making the extension mostly just a wrapper. 

The issue is that the wrapper `surveydown.lua` file used code that doesn't work on Windows, so we modified it to first detect the OS and then search for the `main.lua` file in the installed R package based on the OS. Hopefully that will work.

**Comment by pingfan-hu** [comment]
@beckjacob I've just replied your email, and here are some more comments:

If `surveydown::sd_update_surveydown()` didn't work, try update the package and extension separately.
```r
remotes::install_github("surveydown-dev/surveydown", force = TRUE)
surveydown::sd_update_extension()
```

**Comment by beckjacob** [comment]
I have updated the package and got the error message below. One thing I didnt do in the first place was specifically running the .qmd within an R project. But I did that now. Not sure if that is important.

_```
Error running filter C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:
sh: createProcess: does not exist (No such file or directory)
stack traceback:
	...cal/R/win-library/4.3/surveydown/quarto/filters/main.lua:7: in upvalue 'get_package_file_path'
	...cal/R/win-library/4.3/surveydown/quarto/filters/main.lua:13: in upvalue 'ensure_html_deps'
	...cal/R/win-library/4.3/surveydown/quarto/filters/main.lua:42: in function <...cal/R/win-library/4.3/surveydown/quarto/filters/main.lua:41>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:449: in local 'callback'
	[string "..."]:1789: in field 'withScriptFile'
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:452: in upvalue 'run_emulated_filter_chain'
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:495: in function <...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:476>
stack traceback:
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:449: in local 'callback'
	[string "..."]:1789: in field 'withScriptFile'
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:452: in upvalue 'run_emulated_filter_chain'
	...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:495: in function <...1/RStudio/RESOUR~1/app/bin/quarto/share/filters/main.lua:476>
Main filter path: C:/Users/ra75sey/AppData/Local/R/win-library/4.3/surveydown/quarto/filters/main.lua
Main filter loaded successfully
Cross-platform nested filter loaded successfully
Calling main filter's Pandoc function
```_

**Comment by jhelvy** [comment]
Sorry you're still getting errors. One thing that's making this hard to debug is I don't have a windows machine. That said, it seems the issue is almost certainly that it's looking in the wrong place for the main lua file in the package, so I'm sure it's a matter of time before we find a robust solution. We'll keep working on it.

**Comment by pingfan-hu** [comment]
Hi @beckjacob , I've pushed a newer version of the extension. It's now `v0.2.4`. Would you install and try it out?
Ideally you only need to update the extension:
```r
surveydown::sd_update_extension()
```
But if it doesn't work please also update the R package:
```r
remotes::install_github("surveydown-dev/surveydown", force = TRUE)
```
Please let us know if this update can solve your problem!

**Comment by pingfan-hu** [comment]
Hi @beckjacob , we've pushed a new version and have tested it well on our own PCs. Please update the R package and extension to the newest version and try it out.
You can update both the package and extension simply by running:
```r
surveydown::sd_update_surveydown()
```
If you still get error message of "main.lua file missing", please [reinstall Quarto](https://quarto.org/docs/get-started/).

Please let us know if your survey works properly.

**Comment by pingfan-hu** [comment]
I'll close this issue for now since we've got it solved from our side. If the problem persists please open a new issue and we'll study on it. Thanks!
